version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          path: ./App
